default:
  log:
    level: info
  processes: 8

retrieve:
  url: https://join.fz-juelich.de/services/rest/surfacedata
  networks: all
  stations: all
  sampling: daily
  parameters: [
    albedo,
    aswdir,
    ch4,
    cloudcover,
    co,
    humidity,
    no,
    no2,
    nox,
    o3,
    ox,
    pblheight,
    pm2p5,
    press,
    relhum,
    so2,
    temp,
    totprecip,
    u,
    v,
    wdir,
    wspeed
  ]
  metrics: [
    data_capture,
    average_values,
    daytime_avg,
    nighttime_avg,
    median,
    perc05,
    perc10,
    perc25,
    perc75,
    perc90,
    perc95,
    perc98,
    dma8epa,
    dma8epa_strict,
    dma8epax,
    dma8epax_strict,
    dma8eu,
    dma8eu_strict,
    avgdma8epax,
    drmdmax1h,
    somo10,
    somo10_strict,
    w126,
    w126_24h,
    nvgt060,
    nvgt080
  ]
  sampling: daily
  daterange:
    start: 2005-01-01 00:00
    end: 2020-12-31 23:59
  parameters: [albedo, aswdir, ch4, cloudcover, co, humidity, no, no2, nox, o3, ox, pblheight, pm2p5, press, relhum, so2, temp, totprecip, u, v, wdir, wspeed]
  metrics: [data_capture, average_values, daytime_avg, nighttime_avg, median, perc05, perc10, perc25, perc75, perc90, perc95, perc98, dma8epa, dma8epa_strict, dma8epax, dma8epax_strict, dma8eu, dma8eu_strict, avgdma8epax, drmdmax1h, somo10, somo10_strict, w126, w126_24h, nvgt060, nvgt080]
  output: /Users/jamesmo/projects/suds-air-quality/local/data/dev

match:
  metrics: [mean, std, count]
  metric: dma8epa
  input:
    toar:
      file: /data/MLIA_active_data/data_SUDSAQ/data/toar/toar2.v1.variables.h5
      parameter: 'o3'
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/**/*.nc # Collect from all years
  output:
    by_month: True
    path: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/
