create-gb:
  target: o3 - toar/o3/dma8epa/mean
  train: [aerosol/sul, co]
  train_performance: True
  model:
    kind: GradientBoostingRegressor
    params:
      loss: squared_error
      learning_rate: 0.1
      n_estimators: 200
      max_depth: 3
      random_state: 1
  input:
    sel:
      time: 2012-07
      lat: [10, 80]
      lon: [220, 310]
      vars: [aerosol/sul, o3, co, toar/o3/dma8epa/mean]
    daily:
      momo: [8, 16]
      toar: 0
    momo:
      # regex: /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/*[0-7]/*.nc
      regex: /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/2012/07.nc
    toar:
      # regex: /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/*[0-7]/*.nc
      regex: /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/2012/07.nc

create-gb:
  target: momo.o3 - toar.o3.dma8epa.mean
  train: [momo.aerosol.sul, momo.co, momo.mda8]
  train_performance: True
  model:
    kind: GradientBoostingRegressor
    params:
      random_state: 1
  GroupKFold: True
  output:
    path   : /Users/jamesmo/projects/suds-air-quality/local/runs/1.create-gb/
    model  : True
    scores : True
    predict: True
    inputs : True
    plots  : True
  input:
    sel:
      # time: 2012-07
      lat: [10, 80]
      lon: [220, 310]
      vars: [momo.aerosol.sul, momo.co, momo.o3, momo.mda8, toar.o3.dma8epa.mean]
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      toar:
        vars: [toar.o3.dma8epa.mean]
        time: 0
      momo:
        vars: [momo.aerosol.sul, momo.o3, momo.co]
        time: [8, 16]
    momo:
      # regex: /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/*[0-7]/*.nc
      regex: /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/201[2-4]/07.nc
    toar:
      # regex: /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/*[0-7]/*.nc
      regex: /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[2-4]/07.nc
  log:
    file: /Users/jamesmo/projects/suds-air-quality/local/runs/1.create-gb/run.log

create-optimize-gb:
  target: momo.o3 - toar.o3.dma8epa.mean
  train: [momo.aerosol, momo.sul, momo.co, momo.mda8]
  train_performance: True
  model:
    kind: GradientBoostingRegressor
    params:
      random_state: 1
  GroupKFold: True
  # KFold:
  #   n_splits: 5
  #   shuffle: True
  #   random_state: 1
  hyperoptimize:
    params:
      loss: [squared_error, absolute_error]
      learning_rate: [0.001, 0.01, 0.1]
      n_estimators: [50, 100, 150, 200]
      max_depth: [2, 3, 4]
    GridSearchCV:
      scoring: neg_root_mean_squared_error
      n_jobs: -1
  output:
    path   : /Users/jamesmo/projects/suds-air-quality/local/runs/1.create-optimize-gb/
    model  : True
    scores : True
    predict: True
    inputs : True
    plots  : True
  input:
    sel:
      # time: 2012-07
      lat: [10, 80]
      lon: [220, 310]
      vars: [momo.aerosol.sul, momo.co, momo.o3, momo.mda8, toar.o3.dma8epa.mean]
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      toar:
        vars: [toar.o3.dma8epa.mean]
        time: 0
      momo:
        vars: [momo.aerosol.sul, momo.o3, momo.co]
        time: [8, 16]
    momo:
      # regex: /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/*[0-7]/*.nc
      regex: /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/2012/07.nc
    toar:
      # regex: /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/*[0-7]/*.nc
      regex: /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/2012/07.nc
  log:
    file: /Users/jamesmo/projects/suds-air-quality/local/runs/1.create-optimize-gb/run.log

create-optimize-rf:
  target: o3 - toar/o3/dma8epa/mean
  train: [aerosol/sul, co]
  train_performance: True
  model:
    kind: RandomForestRegressor
    params:
      random_state: 1
  hyperoptimize:
    params:
      criterion: [squared_error, absolute_error]
      max_features: [sqrt, log2, null]
      n_estimators: [50, 100, 150, 200]
      max_depth: [2, 3, 4, null]
    kfold:
      n_splits: 5
      shuffle: True
      random_state: 1
    GridSearchCV:
      scoring: neg_root_mean_squared_error
      n_jobs: -1
  input:
    sel:
      time: 2012-07
      lat: [10, 80]
      lon: [220, 310]
      vars: [aerosol/sul, o3, co, toar/o3/dma8epa/mean]
    daily:
      momo: [8, 16]
      toar: 0
    momo:
      # regex: /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/*[0-7]/*.nc
      regex: /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/2012/07.nc
    toar:
      # regex: /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/*[0-7]/*.nc
      regex: /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/2012/07.nc
  log:
    file: /Users/jamesmo/projects/suds-air-quality/local/logs/create-optimize-rf.1.log

default: # create-rf
  ray: False
  target: momo.mda8 - toar.o3.dma8epa.mean
  train: momo.(?!o3|mda8).*
  train_performance: False
  model:
    kind: RandomForestRegressor
    params:
      random_state: 1
  GroupKFold: True
  permutation_importance:
    random_state: 1
    n_jobs: -1
  treeinterpreter:
    n_jobs: -1
  output:
    path         : /Users/jamesmo/projects/suds-air-quality/local/runs/1.create-rf/
    model        : True
    scores       : True
    predict      : True
    bias         : True
    contributions: True
    importance   : True
    inputs       : True
    plots        : True
  input:
    sel:
      # time: 2012-07
      lat: [10, 80]
      lon: [220, 310]
      vars: [momo.t, momo.u, momo.v, momo.mda8, toar.o3.dma8epa.mean]
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      toar:
        vars: [toar.o3.dma8epa.mean]
        time: 0
      momo:
        vars: momo.(?!mda8).*
        time: [8, 16]
  log:
    level: debug

jan:
  output:
    path: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/jan/rf/
  input:
    glob:
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/201[1-4]/01.nc
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-4]/01.nc
  log:
    file: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/jan/rf/run.log

feb:
  output:
    path: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/feb/rf/
  input:
    glob:
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/201[1-4]/02.nc
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-4]/02.nc
  log:
    file: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/feb/rf/run.log

mar:
  output:
    path: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/mar/rf/
  input:
    glob:
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/201[1-4]/03.nc
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-4]/03.nc
  log:
    file: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/mar/rf/run.log

apr:
  output:
    path: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/apr/rf/
  input:
    glob:
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/201[1-4]/04.nc
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-4]/04.nc
  log:
    file: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/apr/rf/run.log

may:
  output:
    path: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/may/rf/
  input:
    glob:
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/201[1-4]/05.nc
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-4]/05.nc
  log:
    file: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/may/rf/run.log

jun:
  output:
    path: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/jun/rf/
  input:
    glob:
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/201[1-4]/06.nc
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-4]/06.nc
  log:
    file: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/jun/rf/run.log

jul:
  output:
    path: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/jul/rf/
  input:
    glob:
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/201[1-4]/07.nc
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-4]/07.nc
  log:
    file: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/jul/rf/run.log

aug:
  output:
    path: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/aug/rf/
  input:
    glob:
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/201[1-4]/08.nc
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-4]/08.nc
  log:
    file: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/aug/rf/run.log

sep:
  output:
    path: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/sep/rf/
  input:
    glob:
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/201[1-4]/09.nc
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-4]/09.nc
  log:
    file: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/sep/rf/run.log

oct:
  output:
    path: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/oct/rf/
  input:
    glob:
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/201[1-4]/10.nc
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-4]/10.nc
  log:
    file: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/oct/rf/run.log

nov:
  output:
    path: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/nov/rf/
  input:
    glob:
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/201[1-4]/11.nc
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-4]/11.nc
  log:
    file: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/nov/rf/run.log

dec:
  output:
    path: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/dec/rf/
  input:
    glob:
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/momo/201[1-4]/12.nc
      - /Volumes/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-4]/12.nc
  log:
    file: /Users/jamesmo/projects/suds-air-quality/local/runs/11-14/bias/dec/rf/run.log
