#
#
# script.py -c config.yml -s gattaca v4 jan
analysis:
  input:
    lazy: True
    parallel: True
gattaca:
  input:
    lazy: False
    parallel: False
# Version definitions go below this line ---------------------------------------
bias:
  target: momo.mda8

  model:
    kind: RandomForestRegressor
    params:
      random_state: 0
      n_jobs: -1
      max_depth: 30

v4:
  datasets:
    - momo
    - toar
  years: 2011-2015
  train: momo.(?!o3|mda8).*
  train_performance: False
  input:
    sel:
      vars: >
        .+\.(?!
          hno3|oh|pan|q2|sens|so2|T2|taugxs|taugys|taux|tauy|twpc|2dsfc.CFC11
          |2dsfc.CFC113|2dsfc.CFC12|ch2o|cumf0|2dsfc.dms|2dsfc.HCFC22
          |2dsfc.H1211|2dsfc.H1301|2dsfc.mc.oc|2dsfc.dflx.bc|2dsfc.dflx.oc
          |2dsfc.LR.SO2|2dsfc.CH3COOOH|prcpl|2dsfc.C3H7OOH|dqlsc
          |2dsfc.mc.pm25.salt|2dsfc.CH3COO2|u10|2dsfc.dflx.nh4|2dsfc.mc.nh4
          |2dsfc.dflx.dust|2dsfc.mc.pm25.dust|osr|osrc|ssrc|v10|2dsfc.OCS
          |2dsfc.taut|ccoverl|ccoverm|2dsfc.DCDT.HOX|2dsfc.DCDT.OY
          |2dsfc.DCDT.SO2|slrdc|uvabs|dqcum|dqdad|dqdyn|dqvdf|dtdad|cumf
          |ccoverh|prcpc|2dsfc.BrCl|2dsfc.Br2|dtcum|2dsfc.mc.sulf|2dsfc.HOBr
          |dtlsc|2dsfc.Cl2|2dsfc.CH3CCl3|2dsfc.CH3Br|2dsfc.ONMV|2dsfc.MACROOH
          |2dsfc.MACR|2dsfc.HBr
        ).*
    scale: True
    parallel: False
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      momo:
        vars: momo.(?!mda8).*
        time: [8, 15]
        local: True
