#%% Example Usage
# {system}<-v4<-bias[median]<-Asia<-{month}
# {system}<-v4<-bias[median]<-NorthAmerica<-{month}
# {system}<-v4<-bias[median]<-Europe<-{month}
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#
#%% Command: python qsub.py -c ../../research/james/definitions.yml -s ...
# ... -s jan feb mar apr may jun jul aug sep oct nov dec -i "gattaca<-v4<-bias[median]<-Europe"
# ... -s jan feb mar apr may jun jul aug sep oct nov dec -i "gattaca<-v4<-bias[median]<-Asia"
# ... -s jan feb mar apr may jun jul aug sep oct nov dec -i "gattaca<-v4<-bias[median]<-NorthAmerica"
# ... -s jan feb mar apr may jun jul aug sep oct nov dec -i "gattaca<-v4<-toar<-Europe"
#^... -s         mar                         oct         -i "gattaca<-v4<-toar<-Europe"
# ... -s jan feb mar apr may jun jul aug sep oct nov dec -i "gattaca<-v4<-toar<-Asia"
# ... -s jan feb mar apr may jun jul aug sep oct nov dec -i "gattaca<-v4<-toar<-NorthAmerica"
#^... -s                         jul aug                 -i "gattaca<-v4<-toar<-NorthAmerica"
# ... -s jan feb mar apr may jun jul aug sep oct nov dec -i "gattaca<-v4<-mda8<-toar-limited<-Europe"
#^... -s jan                     jul         oct         -i "gattaca<-v4<-mda8<-toar-limited<-Europe"
# ... -s jan feb mar apr may jun jul aug sep oct nov dec -i "gattaca<-v4<-mda8<-toar-limited<-Asia"
# ... -s jan feb mar apr may jun jul aug sep oct nov dec -i "gattaca<-v4<-mda8<-toar-limited<-NorthAmerica"
#^... -s     feb                     aug                 -i "gattaca<-v4<-mda8<-toar-limited<-NorthAmerica"
#%%%%%%%%%%%%%%%%
#%% Extended
# ... -s jan feb mar apr may jun jul aug sep oct nov dec -i "gattaca<-v4<-bias[median]<-extended"
# ... -s jan feb mar apr may jun jul aug sep oct nov dec -i "gattaca<-v4<-toar<-extended"
# ... -s jan feb mar apr may jun jul aug sep oct nov dec -i "gattaca<-v4<-mda8<-toar-limited<-extended"
#%%%%%%%%%%%%%%%%
#%% Full emulator
# ... -s jan feb mar apr may jun jul aug sep oct nov dec -i "gattaca<-v4<-mda8<-cap-leaves"
#%%%%%%%%%%%%%%%%
#%% v5
# ... -s jan feb mar apr may jun jul aug sep oct nov dec -i "gattaca<-v5<-bias[median]"
# ... -s jan feb mar apr may jun jul aug sep oct nov dec -i "gattaca<-v5<-toar"
# ... -s jan feb mar apr may jun jul aug sep oct nov dec -i "gattaca<-v5<-mda8<-toar-limited"
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#
default:
  range: 201[1-5]
  train_performance: False
  GroupKFold: True
  model:
    kind: RandomForestRegressor
    params:
      random_state: 0
      n_jobs: -1
  permutation_importance:
    random_state: 1
    n_jobs: -1
  treeinterpreter:
    n_jobs: -1
  # explain:
  #   resample: True
  output:
    path: ${.env.output}/${.env.type}/${$MODELNAME}/${.month}
    model        : True
    data         : True
    target       : True
    predict      : True
    bias         : True
    contributions: True
    scores       : True
    importance   : True
    plots        : True
    explanation  : True
    quantiles    : True
  plots:
    importances:
      count: 20
      labelrotation: 90
  input:
    lazy: True
    parallel: True
    # chunks:
    #   time: 8
    #   lat: 16
    #   lon: 32
  log:
    file: ${.env.output}/${.env.type}/${$MODELNAME}/${.month}/run.log
    level: debug
    reset: True
    config: ${.env.output}/${.env.type}/${$MODELNAME}/
  dask:
    config:
      distributed.admin.tick.limit: 60s
      distributed.worker.memory.terminate: 0.98
    client:
      dashboard_address: null

# System

gattaca:
  .patch: default
  input:
    parallel: False
  env:
    input: /projects/mlia-active-data/data_SUDSAQ/data
    output: /scratch/sudsaq/models

mlia:
  .patch: default
  env:
    input: /data/MLIA_active_data/data_SUDSAQ/data
    output: /data/MLIA_active_data/data_SUDSAQ/models

mac:
  .patch: default
  env:
    input: /Volumes/MLIA_active_data/data_SUDSAQ/data
    output: /Volumes/MLIA_active_data/data_SUDSAQ/models

# Model choices
RFQ:
  model:
    kind: RandomForestQuantileRegressor
    intervals: # % confidence, 95% confidence = 95
      - 0 # Empirical median prediction == .5 quantile
      - 1
      - 5
      - 10
      - 20
      - 25
      - 30
      - 40
      - 50
      - 60
      - 70
      - 75
      - 80
      - 90
      - 95
      - 99
  permutation_importance: False

# Script-specific arguments (inherit these last)

explain:
  log:
    file: ${.env.output}/${.env.type}/${$MODELNAME}/${.month}/explain.log

# Versions

v4:
  input:
    glob:
      - ${.env.input}/momo/${.range}/${.mon_n}.nc    # MOMO
      - ${.env.input}/toar/v1/${.range}/${.mon_n}.nc # TOAR
    sel:
      # This regex drops these keys
      vars: '[^\.]+\.(?!snow|hno3|oh|pan|q2|sens|so2|T2|taugxs|taugys|taux|tauy|twpc|2dsfc.CFC11|2dsfc.CFC113|2dsfc.CFC12|ch2o|cumf0|2dsfc.dms|2dsfc.HCFC22|2dsfc.H1211|2dsfc.H1301|2dsfc.mc.oc|2dsfc.dflx.bc|2dsfc.dflx.oc|2dsfc.LR.SO2|2dsfc.CH3COOOH|prcpl|2dsfc.C3H7OOH|dqlsc|2dsfc.mc.pm25.salt|2dsfc.CH3COO2|u10|2dsfc.dflx.nh4|2dsfc.mc.nh4|2dsfc.dflx.dust|2dsfc.mc.pm25.dust|osr|osrc|ssrc|v10|2dsfc.OCS|2dsfc.taut|ccoverl|ccoverm|2dsfc.DCDT.HOX|2dsfc.DCDT.OY|2dsfc.DCDT.SO2|slrdc|uvabs|dqcum|dqdad|dqdyn|dqvdf|dtdad|cumf|ccoverh|prcpc|2dsfc.BrCl|2dsfc.Br2|dtcum|2dsfc.mc.sulf|2dsfc.HOBr|dtlsc|2dsfc.Cl2|2dsfc.CH3CCl3|2dsfc.CH3Br|2dsfc.ONMV|2dsfc.MACROOH|2dsfc.MACR|2dsfc.HBr|Restart|agcm|CHEMTMP|SYSIN|gralb|.*gt3|stderr|tcr2).*'
    scale: True
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      toar:
        vars: [toar.mda8.mean]
        time: 0
      momo:
        vars: momo.(?!mda8).*
        time: [8, 15]
        local: True

v5:
  .patch: v4
  input:
    glob:
      - ${.env.input}/momo/${.range}/${.mon_n}.nc              # MOMO
      - ${.env.input}/toar/v2.2/${.range}/${.mon_n}.nc         # TOAR
      - ${.env.input}/gee/modis/*.nc                           # MODIS
      - ${.env.input}/gee/population/pop_2010*.nc              # Population
    daily:
      modis:
        vars: modis.*
        time: 0

v6-gee:
  .patch: v4
  range: 201[3-6]
  input:
    glob:
      - ${.env.input}/momo/${.range}/${.mon_n}.nc              # MOMO
      - ${.env.input}/toar/v2.2/${.range}/${.mon_n}.nc         # TOAR
      - ${.env.input}/gee/modis/*.nc                           # MODIS
      - ${.env.input}/gee/population/pop_2010*.nc              # Population
      - ${.env.input}/gee/nightlight/${.range}/*${.month}*.nc  # Night Light
    daily:
      modis:
        vars: modis.*
        time: 0

v6r:
  input:
    glob:
      - ${.env.input}/momo/${.range}/${.mon_n}.nc       # MOMO
      - ${.env.input}/momo/extra/${.range}/${.mon_n}.nc # MOMO extras
      - ${.env.input}/toar/v1/${.range}/${.mon_n}.nc    # TOAR
    sel:
      vars:
        - momo.2dsfc.BrOX
        - momo.2dsfc.C10H16
        - momo.2dsfc.C2H6
        - momo.2dsfc.C3H6
        - momo.2dsfc.C5H8
        - momo.2dsfc.CH2O
        - momo.2dsfc.H2O2
        - momo.2dsfc.HNO3
        - momo.2dsfc.HO2
        - momo.2dsfc.N2O5
        - momo.2dsfc.NH3
        - momo.2dsfc.OH
        - momo.2dsfc.PAN
        - momo.ccover
        - momo.olr
        - momo.prcp
        - momo.co
        - momo.ps
        - momo.q
        - momo.t
        - momo.u
        - momo.v
        - momo.no
        - momo.no2
        # - momo.pblh
        - momo.noxflux.gt3 # momo.NOxemi ?
        - momo.coflux.gt3 # momo.COemi ?
        - momo.rfluxld
        - momo.rfluxsd
        - momo.mda8
        - toar.mda8.median

# TOAR versions

toar-v1:
  toar:
    mean: toar.o3.dma8epa.mean
    median: toar.o3.dma8epa.median
  input:
    glob:
      - ${.env.input}/momo/${.range}/${.mon_n}.nc    # MOMO
      - ${.env.input}/toar/v1/${.range}/${.mon_n}.nc # TOAR

toar-v2:
  toar:
    mean: toar.mda8.mean
    median: toar.mda8.median
  input:
    glob:
      - ${.env.input}/momo/${.range}/${.mon_n}.nc      # MOMO
      - ${.env.input}/toar/v2.2/${.range}/${.mon_n}.nc # TOAR

# Restrictions

2013-16:
  range: 201[3-6]

2005-19:
  range: 20{0[5-9],1[0-9]}

2005-20:
  range: 20{0[5-9],1[0-9],20}

toar-limited:
  input:
    use_locs_of: toar.mda8.mean

extended:
  # Only 2005 to 2015
  range: 20{0[5-9],1[0-5]}
  input:
    subsample:
      dim: time
      N: 3 # Drop every 3rd sample of time

extended-v2:
  range: 20{0[5-9],1[0-5]}
  treeinterpreter:
    n_jobs: 5

# Cap sections are to limit a model's parameters likely due to the size of the data we're processing
# These sometimes need to disable the truth_vs_predicted plot for the same reason
cap-leaves:
  model:
    params:
      max_leaf_nodes: 100000
  plots:
    truth_vs_predicted: False

cap-depth:
  model:
    params:
      max_depth: 30

# Run Types

bias-median:
  target: momo.mda8 - ${.toar.median}
  train: (?!toar).+\.(?!o3|mda8).*
  input:
    daily:
      toar:
        vars:
          - ${.toar.median}
  env:
    type: bias

bias-mean:
  target: momo.mda8 - ${.toar.mean}
  train: (?!toar).+\.(?!o3|mda8).*
  input:
    daily:
      toar:
        vars:
          - ${.toar.mean}
  env:
    type: bias

toar:
  target: ${.toar.mean}
  train: (?!toar).+\.(?!o3|mda8).*
  env:
    type: toar

mda8:
  target: momo.mda8
  train: momo.(?!o3|mda8).*
  env:
    type: emulator/mda8

o3:
  target: momo.o3
  train: momo.(?!o3|mda8).*
  env:
    type: emulator/o3

oh:
  range: 201[4-5]
  input:
    glob:
      - ${.env.input}/momo/OH/${.range}/${.mon_n}.nc  # MOMO OH
    scale: True
  permutation_importance: False
  output:
    plots: False
  treeinterpreter:
    n_jobs: 10
  log:
    reset: False
  env:
    type: emulator/oh
oh-300:
  .patch: oh
  target: momo.2d300.OH
  train: momo.2d300.(?!OH).*
oh-500:
  .patch: oh
  target: momo.2d500.OH
  train: momo.2d500.(?!OH).*
oh-700:
  .patch: oh
  target: momo.2d700.OH
  train: momo.2d700.(?!OH).*

# Regions

NorthAmerica:
  input:
    sel:
      lat: [20, 55]
      lon: [-125, -70]

Europe:
  input:
    sel:
      lat: [35, 65]
      lon: [-10, 25]

Asia:
  input:
    sel:
      lat: [20, 50]
      lon: [100, 145]

# Months

jan:
  month: jan
  mon_n: '01'

feb:
  month: feb
  mon_n: '02'
  input:
    sel:
      drop_date:
        day: 29

mar:
  month: mar
  mon_n: '03'

apr:
  month: apr
  mon_n: '04'

may:
  month: may
  mon_n: '05'

jun:
  month: jun
  mon_n: '06'

jul:
  month: jul
  mon_n: '07'

aug:
  month: aug
  mon_n: '08'

sep:
  month: sep
  mon_n: '09'

oct:
  month: oct
  mon_n: '10'

nov:
  month: nov
  mon_n: '11'

dec:
  month: dec
  mon_n: '12'

# Preprocessing matching scripts

match-toar:
  metrics:
    - mean
    - median
    - std
  variable: o3.mda8
  input:
    toar:
      file: /Users/jamesmo/projects/sudsaq/dev/.local/data/toar/track-df.mda8.h5
      parameter: null
    momo:
      regex: ${.env.input}/momo/2012/01.nc
  output:
    by_month: False
    path: /Users/jamesmo/projects/sudsaq/dev/.local/data/toar/matched-mda8.v2-3.nc
  log:
    file: null
    level: debug
    config: null
  # mlky:
  #   debug: [__call__]
