default:
  target: momo.mda8 - toar.o3.dma8epa.mean
  train: momo.(?!o3|mda8).*
  train_performance: False
  model:
    kind: RandomForestRegressor
    params:
      random_state: 0
      n_jobs: -1
  GroupKFold: True
  permutation_importance:
    random_state: 0
    n_jobs: -1
  treeinterpreter:
    n_jobs: -1
  explain: False
  output:
    model        : True
    data         : True
    target       : True
    predict      : True
    bias         : True
    contributions: True
    scores       : True
    importance   : True
    plots        : True
    explanation  : True
  plots:
    importances:
      count: 20
      labelrotation: 90
  input:
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      toar:
        vars: [toar.o3.dma8epa.mean]
        time: 0
      momo:
        vars: momo.(?!mda8).* # Match all momo variables except mda8
        time: [8, 15]
        local: False
  log:
    level: debug
    reset: True
    config: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/

jan:
  output:
    path: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/jan/
  input:
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/01.nc         # MOMO
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/01.nc # TOAR
  log:
    file: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/jan/run.log

feb:
  output:
    path: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/feb/
  input:
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/02.nc         # MOMO
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/02.nc # TOAR
  log:
    file: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/feb/run.log

mar:
  output:
    path: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/mar/
  input:
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/03.nc         # MOMO
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/03.nc # TOAR
  log:
    file: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/mar/run.log

apr:
  output:
    path: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/apr/
  input:
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/04.nc         # MOMO
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/04.nc # TOAR
  log:
    file: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/apr/run.log

may:
  output:
    path: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/may/
  input:
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/05.nc         # MOMO
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/05.nc # TOAR
  log:
    file: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/may/run.log

jun:
  output:
    path: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/jun/
  input:
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/06.nc         # MOMO
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/06.nc # TOAR
  log:
    file: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/jun/run.log

jul:
  output:
    path: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/jul/
  input:
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc         # MOMO
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc # TOAR
  log:
    file: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/jul/run.log

aug:
  output:
    path: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/aug/
  input:
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/08.nc         # MOMO
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/08.nc # TOAR
  log:
    file: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/aug/run.log

sep:
  output:
    path: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/sep/
  input:
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/09.nc         # MOMO
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/09.nc # TOAR
  log:
    file: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/sep/run.log

oct:
  output:
    path: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/oct/
  input:
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/10.nc         # MOMO
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/10.nc # TOAR
  log:
    file: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/oct/run.log

nov:
  output:
    path: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/nov/
  input:
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/11.nc         # MOMO
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/11.nc # TOAR
  log:
    file: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/nov/run.log

dec:
  output:
    path: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/dec/
  input:
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/12.nc         # MOMO
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/12.nc # TOAR
  log:
    file: /scratch_lg_edge/sudsaq/models/bias/utc/8hr_mean/v1/dec/run.log
