name: sudsaq
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cartopy
  - dask
  - h5py
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - panel
  - pyyaml
  - rioxarray
  - requests
  - scikit-learn
  - seaborn
  - shap
  - tqdm
  - xarray
  - pip
  - pip:
    - fasttreeshap # requires g++
    - mlky
    - ray
    - tables
