default:
  target: momo.mda8
  train: momo.(?!o3|mda8).*
  train_performance: False
  model:
    kind: RandomForestRegressor
    params:
      random_state: 0
      n_jobs: -1
  GroupKFold: True
  permutation_importance:
    random_state: 1
    n_jobs: -1
  treeinterpreter:
    n_jobs: -1
  explain: False
#  ray:
#    _plasma_directory: /scratch/jamesmo/tmp
#    _temp_dir: /scratch/jamesmo/tmp
  output:
    model        : True
    data         : True
    target       : True
    predict      : True
    bias         : True
    contributions: True
    scores       : True
    importance   : True
    plots        : True
    explanation  : True
  plots:
    importances:
      count: 20
      labelrotation: 90
  input:
    # sel:
      # lat: [10, 80]   # America
      # lon: [220, 310] # America
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
#      toar:
#        vars: [toar.o3.dma8epa.mean]
#        time: 0
      momo:
        vars: momo.(?!mda8).* # Match all momo variables except mda8
        time: [8, 15]
        local: False
  log:
    level: debug
    reset: True
    config: /scratch_lg_edge/sudsaq/src/suds-air-quality/sudsaq/configs/dev/ml/monthly/emulator/utc

jul:
  output:
    path: /scratch_lg_edge/sudsaq/kelsey_exp/jul/
  input:
    glob:
      - /projects/MLIA_active_data/data_SUDSAQ/data/momo/201[1-4]/07.nc         # MOMO
      - /projects/MLIA_active_data/data_SUDSAQ/gee/fire/201[1-4]_fire_globe_mode.nc   # FIRE (YEARLY)
      - /projects/MLIA_active_data/data_SUDSAQ/gee/modis/201[1-4]_modis_globe_mode.nc    # MODIS LC MODE (YEARLY)
      - /projects/MLIA_active_data/data_SUDSAQ/gee/pop/2010_population_density_globe.nc    # POPULATION DATA (5-YEAR)
  log:
    file: /scratch_lg_edge/sudsaq/kelsey_exp/jul/run.log
