default:
  target: momo.o3
  train: (?!toar|momo.o3|momo.mda8).*
  train_performance: False
  model:
    kind: RandomForestRegressor
    params:
      random_state: 0
      n_jobs: -1
      verbose: 10
      max_depth: 30
  GroupKFold: True
  permutation_importance:
    random_state: 0
  treeinterpreter:
    n_jobs: -1
  explain: False
  predict_regions:
    NorthAmerica:
      lat: [10, 80]
      lon: [220, 310]
    WestEurope:
      lat: [30, 75]
      lon: [345, 360]
    EastEurope:
      lat: [30, 75]
      lon: [0, 45]
    EastAsia:
      lat: [30, 55]
      lon: [120, 150]
  output:
    model        : True
    data         : True
    target       : True
    predict      : True
    bias         : True
    contributions: True
    scores       : True
    importance   : True
    plots        : True
    explanation  : True
  plots:
    importances:
      count: 20
      labelrotation: 90
  input:
    parallel: False
    lazy: False
  log:
    level: debug
    reset: True
    config: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/

v1:
  not_ti: True
  input:
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.ch2o, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/v1/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/v1/jul/run.log
v2:
  not_ti: True
  input:
    replace_vals:
      momo.no2:
        bounds: [-0.1, .1]
        value: 1e32
    calc:
      ch2o_no2: momo.ch2o / momo.no2
    sel:
      vars: [ch2o_no2, momo.ps, momo.t, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/v2/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/v2/jul/run.log
v3:
  not_ti: True
  input:
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.co, momo.so2, momo.ch2o, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/v3/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/v3/jul/run.log

v1-ls:
  split_predict: 100
  input:
    sel:
      lat: [40, 140]
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.ch2o, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/lat_sliced/v1/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/lat_sliced/v1/jul/run.log
v2-ls:
  split_predict: 100
  input:
    replace_vals:
      momo.no2:
        bounds: [-0.1, .1]
        value: 1e32
    sel:
      lat: [40, 140]
    calc:
      ch2o_no2: momo.ch2o / momo.no2
    sel:
      vars: [ch2o_no2, momo.ps, momo.t, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/lat_sliced/v2/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/lat_sliced/v2/jul/run.log
v3-ls:
  split_predict: 100
  input:
    sel:
      lat: [40, 140]
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.co, momo.so2, momo.ch2o, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/lat_sliced/v3/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/lat_sliced/v3/jul/run.log

v1_limited:
  use_locs_of: toar.o3.dma8epa.mean
  input:
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.o3, momo.ch2o, toar.o3.dma8epa.mean]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/limited/v1/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/limited/v1/jul/run.log
v2_limited:
  use_locs_of: toar.o3.dma8epa.mean
  input:
    replace_vals:
      momo.no2:
        bounds: [-0.1, .1]
        value: 1e32
    calc:
      ch2o_no2: momo.ch2o / momo.no2
    sel:
      vars: [ch2o_no2, momo.ps, momo.t, momo.o3, toar.o3.dma8epa.mean]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/limited/v2/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/limited/v2/jul/run.log
v3_limited:
  use_locs_of: toar.o3.dma8epa.mean
  input:
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.co, momo.so2, momo.o3, momo.ch2o, toar.o3.dma8epa.mean]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/limited/v3/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/limited/v3/jul/run.log

mda8_v1:
  not_ti: True
  target: momo.mda8
  input:
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.mda8, momo.ch2o, toar.o3.dma8epa.mean]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      toar:
        vars: [toar.o3.dma8epa.mean]
        time: 0
      momo:
        vars: momo.(?!mda8).*
        time: [8, 15]
        local: True
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/full/v1/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/full/v1/jul/run.log
    config: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/
mda8_v1_limited:
  target: momo.mda8
  use_locs_of: toar.o3.dma8epa.mean
  input:
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.mda8, momo.ch2o, toar.o3.dma8epa.mean]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      toar:
        vars: [toar.o3.dma8epa.mean]
        time: 0
      momo:
        vars: momo.(?!mda8).*
        time: [8, 15]
        local: True
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/limited/v1/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/limited/v1/jul/run.log
    config: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/
