default:
  target: momo.o3
  train: (?!toar|momo.o3|momo.mda8).*
  train_performance: False
  model:
    kind: RandomForestRegressor
    params:
      random_state: 0
      n_jobs: -1
      verbose: 10
      max_depth: 30
  GroupKFold: True
  permutation_importance:
    random_state: 0
  treeinterpreter:
    n_jobs: -1
  explain: False
  predict_regions:
    NorthAmerica:
      lat: [10, 80]
      lon: [220, 310]
    WestEurope:
      lat: [30, 75]
      lon: [345, 360]
    EastEurope:
      lat: [30, 75]
      lon: [0, 45]
    EastAsia:
      lat: [30, 55]
      lon: [120, 150]
  output:
    model        : True
    data         : True
    target       : True
    predict      : True
    bias         : True
    contributions: True
    scores       : True
    importance   : True
    plots        : True
    explanation  : True
  plots:
    importances:
      count: 20
      labelrotation: 90
  input:
    parallel: False
    lazy: False
  log:
    level: debug
    reset: True
    config: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/

v1:
  not_ti: True
  input:
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.ch2o, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/v1/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/v1/jul/run.log
v2:
  not_ti: True
  input:
    replace_vals:
      momo.no2:
        bounds: [-0.1, .1]
        value: 1e32
    calc:
      ch2o_no2: momo.ch2o / momo.no2
    sel:
      vars: [ch2o_no2, momo.ps, momo.t, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/v2/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/v2/jul/run.log
v3:
  not_ti: True
  input:
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.co, momo.so2, momo.ch2o, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/v3/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/v3/jul/run.log

v1_noplot:
  not_ti: True
  input:
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.ch2o, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
  output:
    plots: False
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/plotless/v1/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/plotless/v1/jul/run.log
v2_noplot:
  not_ti: True
  input:
    replace_vals:
      momo.no2:
        bounds: [-0.1, .1]
        value: 1e32
    calc:
      ch2o_no2: momo.ch2o / momo.no2
    sel:
      vars: [ch2o_no2, momo.ps, momo.t, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
  output:
    plots: False
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/plotless/v2/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/plotless/v2/jul/run.log
v3_noplot:
  not_ti: True
  input:
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.co, momo.so2, momo.ch2o, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
  output:
    plots: False
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/plotless/v3/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/plotless/v3/jul/run.log

v1-ls:
  split_predict: 100
  input:
    sel:
      lat: [40, 140]
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.ch2o, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/lat_sliced/v1/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/lat_sliced/v1/jul/run.log
v2-ls:
  split_predict: 100
  input:
    replace_vals:
      momo.no2:
        bounds: [-0.1, .1]
        value: 1e32
    sel:
      lat: [40, 140]
    calc:
      ch2o_no2: momo.ch2o / momo.no2
    sel:
      vars: [ch2o_no2, momo.ps, momo.t, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/lat_sliced/v2/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/lat_sliced/v2/jul/run.log
v3-ls:
  split_predict: 100
  input:
    sel:
      lat: [40, 140]
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.co, momo.so2, momo.ch2o, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/lat_sliced/v3/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/lat_sliced/v3/jul/run.log

v1_limited:
  input:
    use_locs_of: toar.o3.dma8epa.mean
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.o3, momo.ch2o, toar.o3.dma8epa.mean]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/limited/v1/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/limited/v1/jul/run.log
v2_limited:
  input:
    use_locs_of: toar.o3.dma8epa.mean
    replace_vals:
      momo.no2:
        bounds: [-0.1, .1]
        value: 1e32
    calc:
      ch2o_no2: momo.ch2o / momo.no2
    sel:
      vars: [ch2o_no2, momo.ps, momo.t, momo.o3, toar.o3.dma8epa.mean]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/limited/v2/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/limited/v2/jul/run.log
v3_limited:
  input:
    use_locs_of: toar.o3.dma8epa.mean
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.co, momo.so2, momo.o3, momo.ch2o, toar.o3.dma8epa.mean]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/limited/v3/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/limited/v3/jul/run.log

mda8_v1:
  not_ti: True
  target: momo.mda8
  input:
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.mda8, momo.ch2o, toar.o3.dma8epa.mean]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      toar:
        vars: [toar.o3.dma8epa.mean]
        time: 0
      momo:
        vars: momo.(?!mda8).*
        time: [8, 15]
        local: True
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/full/v1/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/full/v1/jul/run.log
    config: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/
mda8_v1_noplot:
  not_ti: True
  target: momo.mda8
  input:
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.mda8, momo.ch2o, toar.o3.dma8epa.mean]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      toar:
        vars: [toar.o3.dma8epa.mean]
        time: 0
      momo:
        vars: momo.(?!mda8).*
        time: [8, 15]
        local: True
  output:
    plots: False
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/full/plotless/v1/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/full/plotless/v1/jul/run.log
    config: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/
mda8_v1_limited:
  target: momo.mda8
  input:
    use_locs_of: toar.o3.dma8epa.mean
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.mda8, momo.ch2o, toar.o3.dma8epa.mean]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      toar:
        vars: [toar.o3.dma8epa.mean]
        time: 0
      momo:
        vars: momo.(?!mda8).*
        time: [8, 15]
        local: True
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/limited/v1/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/limited/v1/jul/run.log
    config: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/

mda8_v3:
  target: momo.mda8
  input:
    sel:
      vars: [momo.mda8, momo.no, momo.no2, momo.ps, momo.t, momo.co, momo.so2, momo.ch2o, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      momo:
        vars: momo.(?!mda8).*
        time: [8, 15]
        local: True
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/full/v3/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/full/v3/jul/run.log
    config: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/full/v3/
mda8_v3_limited:
  target: momo.mda8
  input:
    use_locs_of: toar.o3.dma8epa.mean
    sel:
      vars: [momo.mda8, momo.no, momo.no2, momo.ps, momo.t, momo.co, momo.so2, momo.ch2o, toar.o3.dma8epa.mean]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      toar:
        vars: [toar.o3.dma8epa.mean]
        time: 0
      momo:
        vars: momo.(?!mda8).*
        time: [8, 15]
        local: True
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/limited/v3/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/limited/v3/jul/run.log
    config: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/limited/v3/

mda8_v4:
  target: momo.mda8
  input:
    sel:
      vars: (momo|toar).(?!hno3|oh|pan|q2|sens|so2|T2|taugxs|taugys|taux|tauy|twpc|2dsfc.CFC11|2dsfc.CFC113|2dsfc.CFC12|ch2o|cumf0|2dsfc.dms|2dsfc.HCFC22|2dsfc.H1211|2dsfc.H1301|2dsfc.mc.oc|2dsfc.dflx.bc|2dsfc.dflx.oc|2dsfc.LR.SO2|2dsfc.CH3COOOH|prcpl|2dsfc.C3H7OOH|dqlsc|2dsfc.mc.pm25.salt|2dsfc.CH3COO2|u10|2dsfc.dflx.nh4|2dsfc.mc.nh4|2dsfc.dflx.dust|2dsfc.mc.pm25.dust|osr|osrc|ssrc|v10|2dsfc.OCS|2dsfc.taut|ccoverl|ccoverm|2dsfc.DCDT.HOX|2dsfc.DCDT.OY|2dsfc.DCDT.SO2|slrdc|uvabs|dqcum|dqdad|dqdyn|dqvdf|dtdad|cumf|ccoverh|prcpc|2dsfc.BrCl|2dsfc.Br2|dtcum|2dsfc.mc.sulf|2dsfc.HOBr|dtlsc|2dsfc.Cl2|2dsfc.CH3CCl3|2dsfc.CH3Br|2dsfc.ONMV|2dsfc.MACROOH|2dsfc.MACR|2dsfc.HBr).*
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      momo:
        vars: momo.(?!mda8).*
        time: [8, 15]
        local: True
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/full/v4/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/full/v4/jul/run.log
    config: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/full/v4/
mda8_v4_limited:
  target: momo.mda8
  input:
    use_locs_of: toar.o3.dma8epa.mean
    sel:
      vars: (momo|toar).(?!hno3|oh|pan|q2|sens|so2|T2|taugxs|taugys|taux|tauy|twpc|2dsfc.CFC11|2dsfc.CFC113|2dsfc.CFC12|ch2o|cumf0|2dsfc.dms|2dsfc.HCFC22|2dsfc.H1211|2dsfc.H1301|2dsfc.mc.oc|2dsfc.dflx.bc|2dsfc.dflx.oc|2dsfc.LR.SO2|2dsfc.CH3COOOH|prcpl|2dsfc.C3H7OOH|dqlsc|2dsfc.mc.pm25.salt|2dsfc.CH3COO2|u10|2dsfc.dflx.nh4|2dsfc.mc.nh4|2dsfc.dflx.dust|2dsfc.mc.pm25.dust|osr|osrc|ssrc|v10|2dsfc.OCS|2dsfc.taut|ccoverl|ccoverm|2dsfc.DCDT.HOX|2dsfc.DCDT.OY|2dsfc.DCDT.SO2|slrdc|uvabs|dqcum|dqdad|dqdyn|dqvdf|dtdad|cumf|ccoverh|prcpc|2dsfc.BrCl|2dsfc.Br2|dtcum|2dsfc.mc.sulf|2dsfc.HOBr|dtlsc|2dsfc.Cl2|2dsfc.CH3CCl3|2dsfc.CH3Br|2dsfc.ONMV|2dsfc.MACROOH|2dsfc.MACR|2dsfc.HBr).*
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      toar:
        vars: [toar.o3.dma8epa.mean]
        time: 0
      momo:
        vars: momo.(?!mda8).*
        time: [8, 15]
        local: True
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/limited/v4/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/limited/v4/jul/run.log
    config: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/limited/v4/
mda8_v4_noplot:
  not_ti: True
  target: momo.mda8
  input:
    sel:
      vars: (momo|toar).(?!hno3|oh|pan|q2|sens|so2|T2|taugxs|taugys|taux|tauy|twpc|2dsfc.CFC11|2dsfc.CFC113|2dsfc.CFC12|ch2o|cumf0|2dsfc.dms|2dsfc.HCFC22|2dsfc.H1211|2dsfc.H1301|2dsfc.mc.oc|2dsfc.dflx.bc|2dsfc.dflx.oc|2dsfc.LR.SO2|2dsfc.CH3COOOH|prcpl|2dsfc.C3H7OOH|dqlsc|2dsfc.mc.pm25.salt|2dsfc.CH3COO2|u10|2dsfc.dflx.nh4|2dsfc.mc.nh4|2dsfc.dflx.dust|2dsfc.mc.pm25.dust|osr|osrc|ssrc|v10|2dsfc.OCS|2dsfc.taut|ccoverl|ccoverm|2dsfc.DCDT.HOX|2dsfc.DCDT.OY|2dsfc.DCDT.SO2|slrdc|uvabs|dqcum|dqdad|dqdyn|dqvdf|dtdad|cumf|ccoverh|prcpc|2dsfc.BrCl|2dsfc.Br2|dtcum|2dsfc.mc.sulf|2dsfc.HOBr|dtlsc|2dsfc.Cl2|2dsfc.CH3CCl3|2dsfc.CH3Br|2dsfc.ONMV|2dsfc.MACROOH|2dsfc.MACR|2dsfc.HBr).*
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      momo:
        vars: momo.(?!mda8).*
        time: [8, 15]
        local: True
  output:
    plots: False
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/full/plotless/v4/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/full/plotless/v4/jul/run.log
    config: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/smalls/full/v4/
