default:
  target: momo.o3
  train: (?!toar|momo.o3).*
  train_performance: False
  model:
    kind: RandomForestRegressor
    params:
      random_state: 0
      n_jobs: -1
      verbose: 1
  GroupKFold: True
  permutation_importance:
    random_state: 0
    n_jobs: -1
  treeinterpreter:
    n_jobs: -1
  explain: False
  output:
    model        : True
    data         : True
    target       : True
    predict      : True
    bias         : True
    contributions: True
    scores       : True
    importance   : True
    plots        : True
    explanation  : True
  plots:
    importances:
      count: 20
      labelrotation: 90
  input:
    lazy: False
  log:
    level: debug
    reset: True
    config: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/

v1:
  split_predict: 100
  input:
    sel:
      lat: [40, 140]
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/lat_sliced/v1/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/lat_sliced/v1/jul/run.log
v2:
  split_predict: 100
  input:
    sel:
      lat: [40, 140]
    calc:
      ch2o_no2: momo.ch2o / momo.no2
    sel:
      vars: [ch2o_no2, momo.ps, momo.t, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/lat_sliced/v2/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/lat_sliced/v2/jul/run.log
v3:
  split_predict: 100
  input:
    sel:
      lat: [40, 140]
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.co, momo.so2, momo.o3]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/lat_sliced/v3/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/full/lat_sliced/v3/jul/run.log

v1_limited:
  use_locs_of: toar.o3.dma8epa.mean
  input:
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.o3, toar.o3.dma8epa.mean]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/limited/v1/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/limited/v1/jul/run.log
v2_limited:
  use_locs_of: toar.o3.dma8epa.mean
  input:
    calc:
      ch2o_no2: momo.ch2o / momo.no2
    sel:
      vars: [ch2o_no2, momo.ps, momo.t, momo.o3, toar.o3.dma8epa.mean]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/limited/v2/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/limited/v2/jul/run.log
v3_limited:
  use_locs_of: toar.o3.dma8epa.mean
  input:
    sel:
      vars: [momo.no, momo.no2, momo.ps, momo.t, momo.co, momo.so2, momo.o3, toar.o3.dma8epa.mean]
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/07.nc
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc
  output:
    path: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/limited/v3/jul/
  log:
    file: /scratch_lg_edge/sudsaq/models/emulator/utc/o3/smalls/limited/v3/jul/run.log
