default:
  target: toar.o3.dma8epa.mean
  train: (?!toar).+\.(?!o3|mda8).*
  train_performance: False
  model:
    kind: RandomForestRegressor
    params:
      random_state: 0
      n_jobs: -1
  GroupKFold: True
  permutation_importance:
    random_state: 1
    n_jobs: -1
  treeinterpreter:
    n_jobs: -1
  explain:
    resample: True
  output:
    path: /scratch_lg_edge/sudsaq/models/toar/local/mean/v4/${.month}/
    model        : True
    data         : True
    target       : True
    predict      : True
    bias         : True
    contributions: True
    scores       : True
    importance   : True
    plots        : True
    explanation  : True
  plots:
    importances:
      count: 20
      labelrotation: 90
  input:
    glob:
      - /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]/${.month}.nc         # MOMO
      - /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]/${.month}.nc # TOAR
    sel:
      # Drop these variables
      vars: .+\.(?!hno3|oh|pan|q2|sens|so2|T2|taugxs|taugys|taux|tauy|twpc|2dsfc.CFC11|2dsfc.CFC113|2dsfc.CFC12|ch2o|cumf0|2dsfc.dms|2dsfc.HCFC22|2dsfc.H1211|2dsfc.H1301|2dsfc.mc.oc|2dsfc.dflx.bc|2dsfc.dflx.oc|2dsfc.LR.SO2|2dsfc.CH3COOOH|prcpl|2dsfc.C3H7OOH|dqlsc|2dsfc.mc.pm25.salt|2dsfc.CH3COO2|u10|2dsfc.dflx.nh4|2dsfc.mc.nh4|2dsfc.dflx.dust|2dsfc.mc.pm25.dust|osr|osrc|ssrc|v10|2dsfc.OCS|2dsfc.taut|ccoverl|ccoverm|2dsfc.DCDT.HOX|2dsfc.DCDT.OY|2dsfc.DCDT.SO2|slrdc|uvabs|dqcum|dqdad|dqdyn|dqvdf|dtdad|cumf|ccoverh|prcpc|2dsfc.BrCl|2dsfc.Br2|dtcum|2dsfc.mc.sulf|2dsfc.HOBr|dtlsc|2dsfc.Cl2|2dsfc.CH3CCl3|2dsfc.CH3Br|2dsfc.ONMV|2dsfc.MACROOH|2dsfc.MACR|2dsfc.HBr).*
    lazy: False
    scale: True
    parallel: False
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      toar:
        vars: [toar.o3.dma8epa.mean]
        time: 0
      momo:
        vars: momo.(?!mda8).*
        time: [8, 15]
        local: True
  log:
    file: /scratch_lg_edge/sudsaq/models/toar/local/mean/v4/${.month}/run.log
    level: debug
    reset: True
    config: /scratch_lg_edge/sudsaq/models/toar/local/mean/v4/

# Region Definitions -----------------------------------------------------------

NorthAmerica:
  input:
    sel:
      lat: [0, 1]
      lon: [0, 1]

Europe:
  input:
    sel:
      lat: [0, 1]
      lon: [0, 1]

Asia:
  input:
    sel:
      lat: [0, 1]
      lon: [0, 1]


# Month Definitions ------------------------------------------------------------

jan:
  month: jan
  mon_n: 01

feb:
  month: feb
  mon_n: 02

mar:
  month: mar
  mon_n: 03

apr:
  month: apr
  mon_n: 04

may:
  month: may
  mon_n: 05

jun:
  month: jun
  mon_n: 06

jul:
  month: jul
  mon_n: 07

aug:
  month: aug
  mon_n: 08

sep:
  month: sep
  mon_n: 09

oct:
  month: oct
  mon_n: 10

nov:
  month: nov
  mon_n: 11

dec:
  month: dec
  mon_n: 12
