default:
  target: momo.mda8
  train: momo.(?!o3|mda8).*
  train_performance: False
  model:
    kind: RandomForestRegressor
    params:
      random_state: 0
      n_jobs: -1
      max_depth: 5
  GroupKFold: True
  permutation_importance:
    random_state: 1
    n_jobs: -1
  treeinterpreter:
    n_jobs: -1
  explain: False
  output:
    _path: /scratch_lg_edge/sudsaq/models/emulator/utc/mda8/full/v4
    model        : True
    data         : True
    target       : True
    predict      : True
    bias         : True
    contributions: True
    scores       : True
    importance   : True
    plots        : True
    explanation  : True
  plots:
    importances:
      count: 20
      labelrotation: 90
    truth_vs_predicted: False
  input:
    _glob:
      momo: /projects/mlia-active-data/data_SUDSAQ/data/momo/201[1-5]
      toar: /projects/mlia-active-data/data_SUDSAQ/data/toar/matched/201[1-5]
    sel:
      # Drop these variables
      vars: .+\.(?!hno3|oh|pan|q2|sens|so2|T2|taugxs|taugys|taux|tauy|twpc|2dsfc.CFC11|2dsfc.CFC113|2dsfc.CFC12|ch2o|cumf0|2dsfc.dms|2dsfc.HCFC22|2dsfc.H1211|2dsfc.H1301|2dsfc.mc.oc|2dsfc.dflx.bc|2dsfc.dflx.oc|2dsfc.LR.SO2|2dsfc.CH3COOOH|prcpl|2dsfc.C3H7OOH|dqlsc|2dsfc.mc.pm25.salt|2dsfc.CH3COO2|u10|2dsfc.dflx.nh4|2dsfc.mc.nh4|2dsfc.dflx.dust|2dsfc.mc.pm25.dust|osr|osrc|ssrc|v10|2dsfc.OCS|2dsfc.taut|ccoverl|ccoverm|2dsfc.DCDT.HOX|2dsfc.DCDT.OY|2dsfc.DCDT.SO2|slrdc|uvabs|dqcum|dqdad|dqdyn|dqvdf|dtdad|cumf|ccoverh|prcpc|2dsfc.BrCl|2dsfc.Br2|dtcum|2dsfc.mc.sulf|2dsfc.HOBr|dtlsc|2dsfc.Cl2|2dsfc.CH3CCl3|2dsfc.CH3Br|2dsfc.ONMV|2dsfc.MACROOH|2dsfc.MACR|2dsfc.HBr).*
    lazy: False
    scale: True
    parallel: False
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      momo:
        vars: momo.(?!mda8).*
        time: [8, 15]
        local: True
  log:
    level: debug
    reset: True
    config: ${.output._path}/

NorthAmerica:
  input:
    sel:
      lat: [0, 1]
      lon: [0, 1]

Europe:
  input:
    sel:
      lat: [0, 1]
      lon: [0, 1]

Asia:
  input:
    sel:
      lat: [0, 1]
      lon: [0, 1]

jan:
  output:
    path: ${.output._path}/jan/
  input:
    glob:
      - ${.input._glob.momo}/01.nc
      - ${.input._glob.toar}/01.nc
  log:
    file: ${.output._path}/jan/run.log

feb:
  output:
    path: ${.output._path}/feb/
  input:
    glob:
      - ${.input._glob.momo}/02.nc
      - ${.input._glob.toar}/02.nc
  log:
    file: ${.output._path}/feb/run.log

mar:
  output:
    path: ${.output._path}/mar/
  input:
    glob:
      - ${.input._glob.momo}/03.nc
      - ${.input._glob.toar}/03.nc
  log:
    file: ${.output._path}/mar/run.log

apr:
  output:
    path: ${.output._path}/apr/
  input:
    glob:
      - ${.input._glob.momo}/04.nc
      - ${.input._glob.toar}/04.nc
  log:
    file: ${.output._path}/apr/run.log

may:
  output:
    path: ${.output._path}/may/
  input:
    glob:
      - ${.input._glob.momo}/05.nc
      - ${.input._glob.toar}/05.nc
  log:
    file: ${.output._path}/may/run.log

jun:
  output:
    path: ${.output._path}/jun/
  input:
    glob:
      - ${.input._glob.momo}/06.nc
      - ${.input._glob.toar}/06.nc
  log:
    file: ${.output._path}/jun/run.log

jul:
  output:
    path: ${.output._path}/jul/
  input:
    glob:
      - ${.input._glob.momo}/07.nc
      - ${.input._glob.toar}/07.nc
  log:
    file: ${.output._path}/jul/run.log

aug:
  output:
    path: ${.output._path}/aug/
  input:
    glob:
      - ${.input._glob.momo}/08.nc
      - ${.input._glob.toar}/08.nc
  log:
    file: ${.output._path}/aug/run.log

sep:
  output:
    path: ${.output._path}/sep/
  input:
    glob:
      - ${.input._glob.momo}/09.nc
      - ${.input._glob.toar}/09.nc
  log:
    file: ${.output._path}/sep/run.log

oct:
  output:
    path: ${.output._path}/oct/
  input:
    glob:
      - ${.input._glob.momo}/10.nc
      - ${.input._glob.toar}/10.nc
  log:
    file: ${.output._path}/oct/run.log

nov:
  output:
    path: ${.output._path}/nov/
  input:
    glob:
      - ${.input._glob.momo}/11.nc
      - ${.input._glob.toar}/11.nc
  log:
    file: ${.output._path}/nov/run.log

dec:
  output:
    path: ${.output._path}/dec/
  input:
    glob:
      - ${.input._glob.momo}/12.nc
      - ${.input._glob.toar}/12.nc
  log:
    file: ${.output._path}/dec/run.log
