default:
  target: toar.o3.dma8epa.mean
  train: momo.(?!o3|mda8).*
  train_performance: False
  model:
    kind: RandomForestRegressor
    params:
      random_state: 1
      n_jobs: -1
  GroupKFold: True
  permutation_importance:
    random_state: 1
    n_jobs: -1
  treeinterpreter:
    n_jobs: -1
  explain: True
  output:
    model        : True
    data         : True
    target       : True
    predict      : True
    bias         : True
    contributions: True
    scores       : True
    importance   : True
    plots        : True
  plots:
    importances:
      count: 20
      labelrotation: 90
  input:
    # sel:
      # lat: [10, 80]   # America
      # lon: [220, 310] # America
    daily:
      mda8:
        vars: [momo.mda8]
        time: 1
      toar:
        vars: [toar.o3.dma8epa.mean]
        time: 0
      momo:
        vars: momo.(?!mda8).* # Match all momo variables except mda8
        time: [8, 16]

jan:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/jan/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/01.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/01.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/jan/rf/run.log

feb:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/feb/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/02.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/02.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/feb/rf/run.log

mar:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/mar/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/03.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/03.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/mar/rf/run.log

apr:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/apr/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/04.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/04.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/apr/rf/run.log

may:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/may/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/05.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/05.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/may/rf/run.log

jun:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/jun/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/06.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/06.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/jun/rf/run.log

jul:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/jul/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/07.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/jul/rf/run.log

aug:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/aug/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/08.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/08.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/aug/rf/run.log

sep:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/sep/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/09.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/09.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/sep/rf/run.log

oct:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/oct/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/10.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/10.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/oct/rf/run.log

nov:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/nov/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/11.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/11.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/nov/rf/run.log

dec:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/dec/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/12.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/12.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/toar/dec/rf/run.log
