default:
  n_jobs: -1
  log:
    level: debug

jan:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/jan/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/01.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/01.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/jan/rf/run.log

feb:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/feb/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/02.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/02.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/feb/rf/run.log

mar:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/mar/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/03.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/03.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/mar/rf/run.log

apr:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/apr/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/04.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/04.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/apr/rf/run.log

may:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/may/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/05.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/05.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/may/rf/run.log

jun:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/jun/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/06.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/06.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/jun/rf/run.log

jul:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/jul/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/07.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/07.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/jul/rf/run.log

aug:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/aug/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/08.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/08.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/aug/rf/run.log

sep:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/sep/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/09.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/09.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/sep/rf/run.log

oct:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/oct/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/10.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/10.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/oct/rf/run.log

nov:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/nov/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/11.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/11.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/nov/rf/run.log

dec:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/dec/rf/
  input:
    momo:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/momo/201[1-5]/12.nc
    toar:
      regex: /data/MLIA_active_data/data_SUDSAQ/data/toar/matched/201[1-5]/12.nc
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/dec/rf/run.log
