default:
  kind: test
  n_jobs: -1
  log:
    level: debug
  output:
    explanation: True

jan-2012:
  output:
    path: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/jan/rf/2012/
  input:
    data : /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/jan/rf/2012/test.data.nc
    model: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/jan/rf/2012/model.pkl
  log:
    file: /data/MLIA_active_data/data_SUDSAQ/models/2011-2015/bias/jan/rf/run.log
